import pandas as pd
import gc


def aggregate_pos_cash_features(pos_df: pd.DataFrame, pos_cat: list) -> pd.DataFrame:
    """
    Aggregates POS_CASH_balance data into customer-level features.

    Assumes that the input DataFrame has already been One-Hot Encoded 
    and passed through the preprocessor.

    Args:
        pos_df (pd.DataFrame): Preprocessed and Encoded POS_CASH data.
        pos_cat (list): List of categorical (OHE) column names.

    Returns:
        pd.DataFrame: Customer-level POS_CASH features.
    """
    aggregations = {
        'MONTHS_BALANCE': ['max', 'mean', 'size'],
        'SK_DPD': ['max', 'mean'],
        'SK_DPD_DEF': ['max', 'mean']
    }
    
    for col in pos_cat:
        aggregations[col] = ['mean']
        
    pos_agg = pos_df.groupby('SK_ID_CURR').agg(aggregations)
    pos_agg.columns = pd.Index([f"POS_{col}_{stat.upper()}" for col, stat in pos_agg.columns.tolist()])
    
    # Active accounts count
    active_col = 'NAME_CONTRACT_STATUS_Active' # 'NAME_CONTRACT_STATUS_Active' is generated by OHE
    if active_col in pos_df.columns:
        active_counts = pos_df[pos_df[active_col] == 1].groupby('SK_ID_CURR').size()
        pos_agg['POS_ACTIVE_COUNT'] = active_counts
    else:
        pos_agg['POS_ACTIVE_COUNT'] = 0
        
    del pos_df
    gc.collect()
    
    return pos_agg


def build_pos_cash_features(pos_df: pd.DataFrame, pos_cat: list) -> pd.DataFrame:
    """
    Orchestrates the feature engineering pipeline for POS_CASH balance.

    Args:
        pos_df (pd.DataFrame): Preprocessed POS_CASH data.
        pos_cat (list): List of OHE categorical columns.

    Returns:
        pd.DataFrame: Final consolidated features per customer.
    """
    pos_features = aggregate_pos_cash_features(pos_df, pos_cat)
    return pos_features