import optuna
import mlflow
import pandas as pd
import logging
from optuna.pruners import HyperbandPruner
from optuna.samplers import TPESampler
from typing import Type
from src.models.base import BaseModel

logger = logging.getLogger(__name__)


class OptunaHPOTuner:
    """
    Unified Optuna Hyperparameter Optimization Tuner for all BaseModel instances.
    Integrates with SQLite for resume capability and optuna-dashboard.
    Employs Hyperband pruning to early-stop unpromising trials.
    """
    def __init__(self, model_class: Type[BaseModel], db_path: str = "sqlite:///optuna.db", study_name: str = "credit_scoring_hpo"):
        self.model_class = model_class
        self.db_path = db_path
        self.study_name = study_name
        self.study = optuna.create_study(
            direction="maximize",
            study_name=self.study_name,
            storage=self.db_path,
            load_if_exists=True,
            sampler=TPESampler(seed=42),
            pruner=HyperbandPruner(min_resource=1, max_resource=10, reduction_factor=3)
        )

    def optimize(self, X: pd.DataFrame, y: pd.Series, n_trials: int = 50, timeout: int = 3600, n_jobs: int = 1):
        """
        Executes the optimization loop.
        
        Args:
            X (pd.DataFrame): Training features.
            y (pd.Series): Target variable.
            n_trials (int): Number of trials to run.
            timeout (int): Timeout in seconds.
            n_jobs (int): Number of parallel processes.
        """
        logger.info(f"Starting HPO for {self.model_class.__name__}. Study: {self.study_name}")

        def objective(trial):
            with mlflow.start_run(nested=True, run_name=f"trial_{trial.number}"):
                # Instantiate model to extract search space dynamically
                dummy_model = self.model_class()
                params = dummy_model.get_optuna_space(trial)
                
                mlflow.log_params(params)
                
                model = self.model_class(params)
                
                # Perform CV to evaluate hyperparameter set
                try:
                    _, _ = model.cross_validate(X, y, n_splits=3)
                    
                    # Fetch metrics generated by cross_validate
                    run_id = mlflow.active_run().info.run_id
                    client = mlflow.tracking.MlflowClient()
                    mean_auc = client.get_metric_history(run_id, "cv_mean_roc_auc")[-1].value
                    
                    return mean_auc
                except optuna.TrialPruned:
                    mlflow.set_tag("status", "pruned")
                    raise
                except Exception as e:
                    logger.error(f"Trial failed: {str(e)}")
                    raise optuna.TrialPruned()

        self.study.optimize(objective, n_trials=n_trials, timeout=timeout, n_jobs=n_jobs)
        
        self._log_best_results()


    def _log_best_results(self):
        """Logs the best parameters and hyperparameter importance to MLflow"""
        if self.study.best_trial is None or len(self.study.trials) == 0:
            logger.warning("No successful Optuna trials found.")
            return

        logger.info(f"Best Trial: {self.study.best_trial.number} | AUC: {self.study.best_value:.4f}")
        
        mlflow.log_params({f"best_{k}": v for k, v in self.study.best_params.items()})
        mlflow.log_metric("best_cv_auc", self.study.best_value)
            
        try:
            importances = optuna.importance.get_param_importances(self.study)
            mlflow.log_dict(importances, "param_importances.json")
        except Exception as e:
            logger.warning(f"Could not calculate param importances: {str(e)}")